api_keys:
  - "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"

default_model: "deepseek/deepseek-v3-base:free"

openrouter:
  base_url: "https://openrouter.ai/api/v1"
  public_endpoints:
    - "https://openrouter-proxy-91ur.onrender.com/v1/chat/completions"
  rate_limit_cooldown: 0
  key_selection_strategy: "round-robin"
  keys:
    - "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"

requestProxy:
  enabled: false
  url: ""

server:
  host: "0.0.0.0"
  port: 10000
